#From class work
#change-log-file=src/main/resources/db/changelog/liquibase-output
#url=jdbc:postgresql://localhost:5432/testLiquibase
#username=postgres
#password=1234
#driver-class-name=org.postgresql.Driver

#Homework
change-log-file=src/main/resources/db/changelog/output
url=jdbc:postgresql://localhost:5432/tournament
username=postgres
password=1234
driver-class-name=org.postgresql.Driver
